version: "3.8"

services:
  mumble-server:
    image: mumblevoip/mumble-server:latest
    container_name: mumble-server
    restart: unless-stopped
    ports:
      - "64738:64738"
      - "64738:64738/udp"
      - "6502:6502"
    environment:
      - MUMBLE_CONFIG_ICE=tcp -h 0.0.0.0 -p 6502
    volumes:
      - mumble-data:/var/lib/mumble-server

  mumble-bridge:
    build: .
    container_name: mumble-bridge
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "10000:10000" # Port for Ice callbacks
    volumes:
      - mumble-data:/var/lib/mumble-server:rw
    environment:
      - MUMBLE_DB=/var/lib/mumble-server/mumble-server.sqlite
      - BRIDGE_PORT=8082
      - MUMBLE_SERVER_ID=1
      - MUMBLE_ICE_HOST=mumble-server
      - MUMBLE_ICE_PORT=6502
      - BRIDGE_HOST=mumble-bridge
    depends_on:
      - mumble-server

volumes:
  mumble-data:
    driver: local
